version: '3'

services:
  api:
    build: ./api
    ports:
      - 8001:8001
    volumes:
      - ./api/src:/var/www/html/src
    depends_on:
      - postgres
    environment:
      - DATABASE_NAME=contactsystem
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    networks:
      - contact_system_network

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - contact_system_network

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=contactsystem
    networks:
      - contact_system_network

networks:
  contact_system_network:
    driver: bridge
