version: '3'

services:
  php:
    build: ./api
    ports:
      - "8001:8001" 
    volumes:
      - ./api/src:/var/www/html/src
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    # volumes:
    #   - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=contactsystem